# Generated by Django 2.2.4 on 2019-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=50)),
                ('upload_img', models.ImageField(upload_to='images/')),
                ('occupied_color', models.CharField(max_length=50)),
                ('opposite', models.CharField(max_length=50)),
                ('complementary', models.CharField(max_length=50)),
            ],
        ),
    ]
